### ISSUE TITLE
Example for Internal Iframe Source

### ISSUE THREAD

**Issue by ydennisy** [juliandavidmr/vue-frame#11]
Hello,

Would you be able to provide a short example of using this in a root element and then loading all of the children components via iFrames?

**Comment by juliandavidmr** [comment]
is it something like a layout that loads child elements? i.e. a replacement for the `<router-view>` component

**Comment by ydennisy** [comment]
My use case is a little different, it is to encapsulate the styles and code. Having come across this project I was wondering if it was possible to:
- load a root vue iframe component using this project
- then load all other components within the root

**Comment by juliandavidmr** [comment]
Hello, I don't think it's possible to make that example. iframe only (for now) changes the pages defined in the vue-frame components with respect to the `frame` and `url` attributes.
Could you create an example of what you hope to achieve with vue-frame? (It would be an example of what you think, even if it doesn't work)
