### ISSUE TITLE
Use with multiple iframe destinations?

### ISSUE THREAD

**Issue by p0psicles** [juliandavidmr/vue-frame#12]
## Expected Behavior
Have two vue-frame elements that refer to two different iframe elements.
Each vue-frame loads in it's configured iframe.

## Actual Behavior
First vue-frame loads in first iframe. Seconds stays blank.

## Steps to Reproduce the Problem
```
<vue-frame text="'lala'" url="/url/" frame="iframe1" type="button" class="form-control"></vue-frame>
<vue-frame text="lala" url="/url/" frame="iframe2" type="button" class="form-control" ></vue-frame>

 <iframe id="iframe1"></iframe>
 <iframe id="iframe2"></iframe>
```

**Comment by juliandavidmr** [comment]
Hi @p0psicles, could you try the project after uncommenting the following code? [here](https://github.com/juliandavidmr/vue-frame/blob/master/src/App.vue#L38).

The `console.log` should show different values for the `this.frame` value

**Comment by p0psicles** [comment]
Issue was the event wasnt triggered because i had it in a v-btn from vuetify. I used a basic `<a>` tag. And now its working.

So the v-btn breaks it somehow

**Comment by juliandavidmr** [comment]
Surely the veautify component (`v-btn`) runs `stopPropagation` which means that the event is not transmitted to `vue-frame`.

**Comment by p0psicles** [comment]
@juliandavidmr Offtopic but do you know if there is a way of catching an event, for when the iframe has finished loading?

**Comment by juliandavidmr** [comment]
At the moment it is not possible to do what you say in the current version of the package, but it is a feature you might add in the future.  I'll do my best to get that new feature out in the next few days.

**Comment by p0psicles** [comment]
Ow that would be awesome

**Comment by p0psicles** [comment]
Do you want me to create a separate feature request?

**Comment by juliandavidmr** [comment]
I think it's a good idea if you do that. Thanks 😉
