### ISSUE TITLE
Deprecation: Synchronous XMLHttpRequest

### ISSUE THREAD

**Issue by nelhop** [juliandavidmr/vue-frame#16]
Chrome DevTools gives this warning:
```
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

How can this be fixed?

**Comment by juliandavidmr** [comment]
Hi @nelhop, can you give me more details or an example to recreate the problem?

**Comment by nelhop** [comment]
Sorry @juliandavidmr, the warning came from the page I loaded with vue-frame frame and not from vue-frame itself.
I think you can close that issue. Again, sorry for the bother!
