### ISSUE TITLE
Is it possible to render iframe immediately, without the clicking on div?

### ISSUE THREAD

**Issue by YevheniiHerasymchuk** [juliandavidmr/vue-frame#7]

**Comment by juliandavidmr** [comment]
Hi @YevheniiHerasymchuk , do you want something like uploading default sites without click event?, if so then it is not possible at the moment, but it could be added in the future.

**Comment by juliandavidmr** [comment]
The default site load is now available, for more information see `default` in the table ["proptypes"](https://github.com/juliandavidmr/vue-frame#proptypes).

This feature has been added in version [1.0.6](https://github.com/juliandavidmr/vue-frame/releases/tag/v1.0.6)

**Comment by juliandavidmr** [comment]
This issue will be closed. If you have more questions about this topic then you can reopen this issue, or you can create a new issue. Oh, thank you.

**Comment by msouidi309** [comment]
Hi, i'm interested on how we display without clicking ?

**Comment by YevheniiHerasymchuk** [comment]
By using simple `<iframe>` tag. I solved other issues in another way but this case was handled by using simple `<iframe` tag only
